/* This file is auto-generated by (yogi loader) */

/**
 * YUI 3 module metadata
 * @module loader
 * @submodule loader-yui3
 */
YUI.Env[Y.version].modules = YUI.Env[Y.version].modules || {
    "gallery-button-plugin": {
        "optional": [
            "cssbutton"
        ],
        "requires": [
            "node"
        ]
    },
    "gallery-flyweight-tree": {
        "requires": [
            "widget",
            "base-build"
        ],
        "skinnable": false
    },
    "gallery-fwt-menu": {
        "requires": [
            "gallery-flyweight-tree",
            "widget",
            "base-build"
        ],
        "skinnable": true
    },
    "gallery-fwt-treeview": {
        "requires": [
            "gallery-flyweight-tree",
            "widget",
            "base-build"
        ],
        "skinnable": true
    },
    "gallery-makenode": {
        "requires": [
            "substitute",
            "classnamemanager"
        ]
    },
    "gallery-md-accordion": {
        "optional": [
            "resize-plugin",
            "transition"
        ],
        "requires": [
            "widget",
            "widget-parent",
            "widget-child",
            "widget-stdmod",
            "gallery-makenode"
        ],
        "skinnable": true
    },
    "gallery-md-button": {
        "requires": [
            "base-build",
            "widget",
            "gallery-makenode"
        ],
        "skinnable": true
    },
    "gallery-md-button-group": {
        "requires": [
            "base-base",
            "widget-parent",
            "widget-child",
            "gallery-makenode",
            "gallery-md-button"
        ],
        "skinnable": true
    },
    "gallery-md-fieldgroup": {
        "requires": [
            "base-build",
            "widget",
            "widget-parent",
            "widget-child",
            "gallery-makenode"
        ],
        "skinnable": true
    },
    "gallery-md-ibutton": {
        "requires": [
            "base-build",
            "widget",
            "gallery-makenode",
            "anim"
        ],
        "skinnable": true
    },
    "gallery-md-inputfield": {
        "optional": [
            "panel"
        ],
        "requires": [
            "base-build",
            "widget",
            "widget-child",
            "gallery-makenode",
            "event-valuechange"
        ],
        "skinnable": true
    },
    "gallery-md-model": {
        "requires": [
            "base"
        ]
    },
    "gallery-md-spinner": {
        "requires": [
            "base-build",
            "event-key",
            "widget",
            "node-focusmanager",
            "gallery-makenode"
        ],
        "skinnable": true
    },
    "gallery-md-timespinner": {
        "requires": [
            "gallery-md-spinner",
            "gallery-makenode"
        ]
    },
    "gallery-stdmod": {
        "requires": [
            "widget-stdmod"
        ]
    },
    "gallery-timeline": {
        "requires": [
            "node",
            "io-base",
            "base",
            "event-mousewheel",
            "event-gestures",
            "classnamemanager",
            "datatype",
            "event-hover"
        ],
        "skinnable": true
    }
};
YUI.Env[Y.version].md5 = 'a67a0ee1b886eb34ef7fd9cd85bf291c';
